apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: 
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
      app.kubernetes.io/instance: backend
  replicas: 1
  template:
    metadata: 
      labels:
        app.kubernetes.io/name: demo
        app.kubernetes.io/instance: backend
    spec:
      containers:
        - name: backend
          image: ccr.ccs.tencentyun.com/koderover-public/backend:latest
          imagePullPolicy: Always 
          command:
            - /workspace/demo
          ports:
            - protocol: TCP
              containerPort: 20219
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: backend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 20219
      targetPort: 20219
     